### ISSUE TITLE
login failed for rsa_pubkey_undefined

### ISSUE THREAD

**Issue by alexandrim0** [emqx/emqx-auth-jwt#84]
The option auth.jwt.pubkey = etc/certs/jwt_public_key.pem defined correctly and file exists. Pubkey is also correct and it works well with other software.
Also plugin works with HMAC but not RSA256 pub key. I can see only "login failed for rsa_pubkey_undefined" in debug log but it is not a clue. What is wrong and what should I do to fix this error? 

Thank you!

**Comment by alexandrim0** [comment]
Could you say which format pubkey should be: "BEGIN PUBLIC KEY" or "BEGIN RSA PUBLIC KEY" or whatever else?

Thank you!

**Comment by HJianBo** [comment]
Yes, it is. However, in the 3.x version, it has a bug that the plugin can not read the `pubkey` file.

We have fixed and released at v3.2.-rc.1

**Comment by alexandrim0** [comment]
I had tested that release today. Still no luck.
Should it be a special type of pubkey?

**Comment by HJianBo** [comment]
Nope, the RSA256 should be work well. Could you paste the config file and error log to help me reproduce it

**Comment by alexandrim0** [comment]
config:
`auth.jwt.from = password
auth.jwt.pubkey = etc/certs/jwt.pem`

output:
`docker exec emqx-dev emqx_ctl plugins load emqx_auth_jwt
=ERROR REPORT==== 24-Jun-2019::11:39:02.985663 ===
[Plugins] Load plugin emqx_auth_jwt failed, cannot start plugin emqx_auth_jwt for {bad_return,
                                                                                   {{emqx_auth_jwt_app,
                                                                                     start,
                                                                                     [normal,
                                                                                      []]},
                                                                                    {'EXIT',
                                                                                     {{badmatch,
                                                                                       {error,
                                                                                        enoent}},
                                                                                      [{emqx_auth_jwt_app,
                                                                                        read_pubkey,
                                                                                        0,
                                                                                        [{file,
                                                                                          "/emqx_rel/_build/emqx/lib/emqx_auth_jwt/src/emqx_auth_jwt_app.erl"},
                                                                                         {line,
                                                                                          63}]},
                                                                                       {emqx_auth_jwt_app,
                                                                                        auth_env,
                                                                                        0,
                                                                                        [{file,
                                                                                          "/emqx_rel/_build/emqx/lib/emqx_auth_jwt/src/emqx_auth_jwt_app.erl"},
                                                                                         {line,
                                                                                          55}]},
                                                                                       {emqx_auth_jwt_app,
                                                                                        start,
                                                                                        2,
                                                                                        [{file,
                                                                                          "/emqx_rel/_build/emqx/lib/emqx_auth_jwt/src/emqx_auth_jwt_app.erl"},
                                                                                         {line,
                                                                                          33}]},
                                                                                       {application_master,
                                                                                        start_it_old,
                                                                                        4,
                                                                                        [{file,
                                                                                          "application_master.erl"},
                                                                                         {line,
                                                                                          277}]}]}}}}
load plugin error: {emqx_auth_jwt,
                    {bad_return,
                     {{emqx_auth_jwt_app,start,[normal,[]]},
                      {'EXIT',
                       {{badmatch,{error,enoent}},
                        [{emqx_auth_jwt_app,read_pubkey,0,
                          [{file,
                            "/emqx_rel/_build/emqx/lib/emqx_auth_jwt/src/emqx_auth_jwt_app.erl"},
                           {line,63}]},
                         {emqx_auth_jwt_app,auth_env,0,
                          [{file,
                            "/emqx_rel/_build/emqx/lib/emqx_auth_jwt/src/emqx_auth_jwt_app.erl"},
                           {line,55}]},
                         {emqx_auth_jwt_app,start,2,
                          [{file,
                            "/emqx_rel/_build/emqx/lib/emqx_auth_jwt/src/emqx_auth_jwt_app.erl"},
                           {line,33}]},
                         {application_master,start_it_old,4,
                          [{file,"application_master.erl"},{line,277}]}]}}}}}`

Sorry about formatting.

**Comment by HJianBo** [comment]
The `{error, enoent}` show that the emqx can not read the ` etc/certs/jwt.pem` file. Plz check it

**Comment by alexandrim0** [comment]
With version v3.2.-rc.2 plugin JWT auth with pubkey works well. Thank you!
